import { User } from "@/types/auth";

export const MOCK_USERS: User[] = [
  {
    id: "user-res-alpha",
    role: "researcher",
    displayName: "Dr. Elena Vance (Researcher Alpha)",
    dateOfBirth: "1994-05-15",
    age: 32,
    sex: "female",
    ageGroup: "25–34",
    institutionalId: "RES-ALPHA-2026",
    createdAt: "2025-11-01T08:00:00Z",
    permissions: [
      "own_profile",
      "experiments",
      "participants",
      "cohort_analytics",
      "experiment_results",
      "leaderboard",
      "exports",
      "research_library",
      "age_analytics",
    ],
  },
  {
    id: "part-001",
    role: "participant",
    displayName: "Participant P-001",
    dateOfBirth: "2010-02-14",
    age: 16,
    sex: "female",
    ageGroup: "15–17",
    createdAt: "2026-03-24T10:14:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
  {
    id: "part-002",
    role: "participant",
    displayName: "Participant P-002",
    dateOfBirth: "2007-06-18",
    age: 19,
    sex: "male",
    ageGroup: "18–24",
    createdAt: "2026-03-23T14:20:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
  {
    id: "part-003",
    role: "participant",
    displayName: "Participant P-003",
    dateOfBirth: "2004-09-10",
    age: 22,
    sex: "female",
    ageGroup: "18–24",
    createdAt: "2026-03-22T11:00:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
  {
    id: "part-004",
    role: "participant",
    displayName: "Participant P-004",
    dateOfBirth: "1998-04-12",
    age: 28,
    sex: "male",
    ageGroup: "25–34",
    createdAt: "2026-03-21T09:30:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
  {
    id: "part-005",
    role: "participant",
    displayName: "Participant P-005",
    dateOfBirth: "1989-11-20",
    age: 37,
    sex: "prefer_not_to_say",
    ageGroup: "35–44",
    createdAt: "2026-03-20T16:00:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
  {
    id: "part-006",
    role: "participant",
    displayName: "Participant P-006",
    dateOfBirth: "1980-08-05",
    age: 46,
    sex: "male",
    ageGroup: "45–54",
    createdAt: "2026-03-19T13:40:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
  {
    id: "part-007",
    role: "participant",
    displayName: "Participant P-007",
    dateOfBirth: "1968-01-30",
    age: 58,
    sex: "female",
    ageGroup: "55+",
    createdAt: "2026-03-18T15:10:00Z",
    permissions: ["own_profile", "own_results", "own_trials", "own_statistics"],
  },
];

export const DEFAULT_USER = MOCK_USERS[0]; // Researcher Alpha
